export interface SessionTracking{
    head_pos_x: number,
    head_pos_y: number,
    head_pos_z: number,
    handR_pos_x: number,
    handR_pos_y: number,
    handR_pos_z: number,
    handR_rot_x: number,
    handR_rot_y: number,
    handR_rot_z: number,
    handR_speed_x: number,
    handR_speed_y: number,
    handR_speed_z: number,
    handL_pos_x: number,
    handL_pos_y: number,
    handL_pos_z: number,
    handL_rot_x: number,
    handL_rot_y: number,
    handL_rot_z: number,
    handL_speed_x: number,
    handL_speed_y: number,
    handL_speed_z: number,
}