export interface SessionData{
    session_date: number,
    session_time: string,
    n_goals: number,
    n_saves: number,
    shoots_initial_time: string,
    shoots_final_time: string,
    shoots_initial_point: string,
    shoots_initial_zone: string,
    shoots_final_point: string,
    shoots_final_zone: string,
    shoots_result: string,
    save_hand: string,
    target_goals: number,
}