export interface SessionTracking{
    session_date: string,
    HeadPosition_x: number,
    HeadPosition_y: number,
    HeadPosition_z: number,
    RHandPosition_x: number,
    RHandPosition_y: number,
    RHandPosition_z: number,
    RHandRotation_x: number,
    RHandRotation_y: number,
    RHandRotation_z: number,
    RHandVelocity_x: number,
    RHandVelocity_y: number,
    RHandVelocity_z: number,
    LHandPosition_x: number,
    LHandPosition_y: number,
    LHandPosition_z: number,
    LRHandRotation_x: number,
    LRHandRotation_y: number,
    LRHandRotation_z: number,
    LHandVelocity_x: number,
    LHandVelocity_y: number,
    LHandVelocity_z: number,
}